import { NextRequest, NextResponse } from 'next/server'
import { auth } from '@clerk/nextjs/server'
import { db, users, diagnosticResponses, progress, purchases, diagnosticSummaries } from '../../../db'
import { eq, and } from 'drizzle-orm'

export async function POST(request: NextRequest) {
  try {
    const { userId } = await auth()
    
    if (!userId) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const { type, dayNumber, dayContent } = await request.json()

    // Get user data
    const userResult = await db.select().from(users).where(eq(users.id, userId)).limit(1)
    if (!userResult || userResult.length === 0) {
      return NextResponse.json({ error: 'User not found' }, { status: 404 })
    }

    const user = userResult[0]
    const safetyData = typeof user.safety === 'string' ? JSON.parse(user.safety) : user.safety

    // Handle different export types
    switch (type) {
      case 'diagnostic-summary-txt':
        return await handleDiagnosticSummaryTXT(userId, safetyData)
      
      case 'diagnostic-comprehensive-txt':
        return await handleDiagnosticComprehensiveTXT(userId, safetyData)
      
      case 'program-structure-txt':
        return await handleProgramStructureTXT(userId, safetyData)
      
      case 'program-daily-txt':
        return await handleProgramDailyTXT(userId, safetyData, dayNumber, dayContent)
      
      case 'diagnostic-questions-txt':
        return await handleDiagnosticQuestionsTXT(userId)
      
      default:
        return NextResponse.json({ error: 'Invalid export type' }, { status: 400 })
    }

  } catch (error) {
    console.error('Error exporting data:', error)
    return NextResponse.json(
      { error: 'Failed to export data' },
      { status: 500 }
    )
  }
}

async function handleDiagnosticSummaryTXT(userId: string, safetyData: any) {
  const summary = safetyData.diagnosticSummary?.content || 'No diagnostic summary available'
  const keyInsights = safetyData.keyInsights || 'No key insights available'
  
  const text = `🔍 DIAGNOSTIC SUMMARY REPORT
Your personalized trauma analysis & healing insights
Generated on ${new Date().toLocaleDateString()}

================================================================================

📋 EXECUTIVE SUMMARY
================================================================================

${summary}

================================================================================

💡 KEY INSIGHTS
================================================================================

${keyInsights}

================================================================================

End of Report
Generated by Unfuck Your Past - AI-Driven Healing Platform`

  return NextResponse.json({
    success: true,
    data: text,
    filename: `diagnostic-summary-${userId}-${Date.now()}.txt`,
    mimeType: 'text/plain'
  })
}

async function handleDiagnosticComprehensiveTXT(userId: string, safetyData: any) {
  try {
    // Get comprehensive report from database
    const reportResult = await db
      .select()
      .from(diagnosticSummaries)
      .where(and(
        eq(diagnosticSummaries.userId, userId),
        eq(diagnosticSummaries.type, 'comprehensive_report')
      ))
      .limit(1)

    if (!reportResult || reportResult.length === 0) {
      return NextResponse.json({
        success: true,
        data: 'No comprehensive diagnostic report found. Please purchase and generate the full report first.',
        filename: `diagnostic-comprehensive-${userId}-${Date.now()}.txt`,
        mimeType: 'text/plain'
      })
    }

    const report = reportResult[0].summary

    const text = `🔍 COMPREHENSIVE DIAGNOSTIC REPORT
Your complete trauma analysis, healing roadmap & actionable recommendations
Generated on ${new Date().toLocaleDateString()}

================================================================================

${report}

================================================================================

End of Comprehensive Report
Generated by Unfuck Your Past - AI-Driven Healing Platform`

    return NextResponse.json({
      success: true,
      data: text,
      filename: `diagnostic-comprehensive-${userId}-${Date.now()}.txt`,
      mimeType: 'text/plain'
    })

  } catch (error) {
    console.error('Error generating comprehensive report TXT:', error)
    return NextResponse.json({
      success: false,
      error: 'Failed to generate comprehensive report'
    }, { status: 500 })
  }
}

async function handleProgramStructureTXT(userId: string, safetyData: any) {
  const programData = safetyData.programStructure || 'No program structure available'
  
  const text = `🌱 30-DAY HEALING PROGRAM STRUCTURE
Your personalized healing journey overview
Generated on ${new Date().toLocaleDateString()}

================================================================================

${programData}

================================================================================

End of Program Structure
Generated by Unfuck Your Past - AI-Driven Healing Platform`

  return NextResponse.json({
    success: true,
    data: text,
    filename: `program-structure-${userId}-${Date.now()}.txt`,
    mimeType: 'text/plain'
  })
}

async function handleProgramDailyTXT(userId: string, safetyData: any, dayNumber: number, dayContent: any) {
  if (!dayContent || !dayContent.content) {
    return NextResponse.json({
      success: false,
      error: 'No daily content provided'
    }, { status: 400 })
  }

  const text = `🌱 DAY ${dayNumber} - HEALING JOURNEY
Your personalized daily healing practice
Generated on ${new Date().toLocaleDateString()}

================================================================================

🎯 MAIN FOCUS: ${dayContent.content.mainFocus || 'Daily Healing'}

================================================================================

🌅 GUIDED PRACTICE
================================================================================

${dayContent.content.guidedPractice || 'No guided practice available'}

================================================================================

⚡ DAILY CHALLENGE
================================================================================

${dayContent.content.challenge || 'No daily challenge available'}

================================================================================

📝 JOURNALING PROMPT
================================================================================

${dayContent.content.journalingPrompt || 'No journaling prompt available'}

================================================================================

🌙 REFLECTION
================================================================================

${dayContent.content.reflection || 'No reflection available'}

================================================================================

🌤️ WEATHER & ENVIRONMENT
================================================================================

${dayContent.content.weather || 'No weather information available'}

================================================================================

😴 SLEEP & WELLNESS
================================================================================

${dayContent.content.sleep || 'No sleep information available'}

================================================================================

🌿 HOLISTIC HEALING BONUS
================================================================================

${dayContent.content.holistic || 'No holistic healing bonus available'}

================================================================================

End of Day ${dayNumber}
Generated by Unfuck Your Past - AI-Driven Healing Platform`

  return NextResponse.json({
    success: true,
    data: text,
    filename: `day-${dayNumber}-${userId}-${Date.now()}.txt`,
    mimeType: 'text/plain'
  })
}

async function handleDiagnosticQuestionsTXT(userId: string) {
  try {
    // Fetch all diagnostic responses with questions and AI insights
    const responses = await db
      .select({
        question: diagnosticResponses.question,
        response: diagnosticResponses.response,
        insight: diagnosticResponses.insight,
        timestamp: diagnosticResponses.createdAt
      })
      .from(diagnosticResponses)
      .where(eq(diagnosticResponses.userId, userId))
      .orderBy(diagnosticResponses.createdAt)

    if (!responses || responses.length === 0) {
      return NextResponse.json({
        success: true,
        data: 'No diagnostic responses found. Please complete the diagnostic section first.',
        filename: `diagnostic-questions-${userId}-${Date.now()}.txt`,
        mimeType: 'text/plain'
      })
    }

    let text = `🔍 DIAGNOSTIC QUESTIONS & ANSWERS WITH AI INSIGHTS
Your complete diagnostic journey with personalized AI analysis
Generated on ${new Date().toLocaleDateString()}

================================================================================

📊 TOTAL RESPONSES: ${responses.length}
================================================================================

`

    responses.forEach((resp, index) => {
      const questionText = resp.question && typeof resp.question === 'object' && 'text' in resp.question ? (resp.question as any).text || `Question ${index + 1}` : `Question ${index + 1}`
      const timestamp = resp.timestamp ? new Date(resp.timestamp).toLocaleString() : 'Unknown time'
      
      text += `\n${'='.repeat(80)}\n`
      text += `QUESTION ${index + 1}: ${questionText}\n`
      text += `Timestamp: ${timestamp}\n`
      text += `${'='.repeat(80)}\n\n`
      
      text += `📝 YOUR RESPONSE:\n`
      text += `${resp.response}\n\n`
      
      text += `🤖 AI INSIGHT:\n`
      text += `${resp.insight || 'No AI insight available'}\n\n`
      
      text += `${'='.repeat(80)}\n\n`
    })

    text += `\n================================================================================\n`
    text += `End of Diagnostic Report\n`
    text += `Generated by Unfuck Your Past - AI-Driven Healing Platform\n`
    text += `Total Questions Answered: ${responses.length}`

    return NextResponse.json({
      success: true,
      data: text,
      filename: `diagnostic-questions-${userId}-${Date.now()}.txt`,
      mimeType: 'text/plain'
    })

  } catch (error) {
    console.error('Error generating diagnostic questions TXT:', error)
    return NextResponse.json({
      success: false,
      error: 'Failed to generate diagnostic questions report'
    }, { status: 500 })
  }
}

export async function GET(request: NextRequest) {
  try {
    const { userId } = await auth()
    
    if (!userId) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    // Get user data
    const userResult = await db.select().from(users).where(eq(users.id, userId)).limit(1)
    if (!userResult || userResult.length === 0) {
      return NextResponse.json({ error: 'User not found' }, { status: 404 })
    }

    const user = userResult[0]
    const safetyData = typeof user.safety === 'string' ? JSON.parse(user.safety) : user.safety

    // Get diagnostic responses
    const answersResult = await db.select({
      question: diagnosticResponses.question,
      content: diagnosticResponses.response,
      summary: diagnosticResponses.insight,
      createdAt: diagnosticResponses.createdAt
    })
    .from(diagnosticResponses)
    .where(eq(diagnosticResponses.userId, userId))
    .orderBy(diagnosticResponses.createdAt)

    // Get program progress
    const progressResult = await db.select({
      day: progress.day,
      completedAt: progress.completedAt
    })
    .from(progress)
    .where(eq(progress.userId, userId))
    .orderBy(progress.day)

    // Get purchases
    const purchasesResult = await db.select({
      product: purchases.product,
      createdAt: purchases.createdAt,
      active: purchases.active
    })
    .from(purchases)
    .where(eq(purchases.userId, userId))
    .orderBy(purchases.createdAt)

    // Format data for export
    const exportData = {
      user: {
        id: userId,
        preferences: {
          tone: user.tone || 'gentle',
          voice: user.voice || 'friend',
          rawness: user.rawness || 'moderate',
          depth: user.depth || 'moderate',
          learning: user.learning || 'text',
          engagement: user.engagement || 'passive'
        }
      },
      diagnostic: {
        responses: answersResult.map(answer => ({
          question: answer.question,
          response: answer.content || '',
          insight: answer.summary || '',
          timestamp: answer.createdAt?.toISOString() || ''
        })),
        summary: safetyData.diagnosticSummary?.content || 'No diagnostic summary available'
      },
      program: {
        progress: {
          completed: progressResult.length,
          total: 30,
          percentage: Math.round((progressResult.length / 30) * 100),
          currentDay: progressResult.length > 0 ? Math.max(...progressResult.map(p => p.day)) + 1 : 1,
          streak: calculateStreak(progressResult.map(p => p.day))
        },
        completedDays: progressResult.map(p => ({
          day: p.day,
          title: `Day ${p.day}`,
          completedAt: p.completedAt?.toISOString() || ''
        }))
      },
      purchases: purchasesResult.map(p => ({
        product: p.product,
        purchasedAt: p.createdAt?.toISOString() || '',
        active: p.active ?? false
      }))
    }

    return NextResponse.json(exportData)

  } catch (error) {
    console.error('Error exporting data:', error)
    return NextResponse.json(
      { error: 'Failed to export data' },
      { status: 500 }
    )
  }
}

function calculateStreak(completedDays: number[]): number {
  if (completedDays.length === 0) return 0
  
  let streak = 0
  const sortedDays = completedDays.sort((a, b) => a - b)
  
  for (let i = 1; i <= Math.max(...sortedDays); i++) {
    if (sortedDays.includes(i)) {
      streak++
    } else {
      break
    }
  }
  
  return streak
}
