import { NextRequest, NextResponse } from 'next/server'
import { auth } from '@clerk/nextjs/server'
import { db, users } from '../../../../db'
import { eq } from 'drizzle-orm'

// Global flag to prevent multiple simultaneous generations
let isGeneratingQuestions = false

export async function GET(request: NextRequest) {
  try {
    const { userId } = await auth()
    
    if (!userId) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    // Get user preferences from database using Drizzle ORM
    const userResult = await db.select().from(users).where(eq(users.id, userId)).limit(1)

    if (!userResult || userResult.length === 0) {
      return NextResponse.json({ error: 'User preferences not found. Please complete onboarding first.' }, { status: 404 })
    }

    const user = userResult[0]
    const safetyData = typeof user.safety === 'string' ? JSON.parse(user.safety) : user.safety

    console.log('User safety data:', JSON.stringify(safetyData, null, 2))

    // Check if personalized questions exist
    const personalizedQuestions = safetyData.personalizedQuestions
    const diagnosticAnalysis = safetyData.diagnosticAnalysis

    if (personalizedQuestions && diagnosticAnalysis && personalizedQuestions.length > 0) {
      console.log('Using existing personalized questions:', personalizedQuestions.length)
      // Use personalized questions
      return NextResponse.json({
        questions: personalizedQuestions,
        userPreferences: {
          tone: user.tone || 'gentle',
          voice: user.voice || 'friend',
          rawness: user.rawness || 'moderate',
          depth: user.depth || 'moderate',
          learning: user.learning || 'text',
          engagement: user.engagement || 'passive',
          goals: safetyData.goals || [],
          experience: safetyData.experience || 'beginner'
        },
        analysis: diagnosticAnalysis,
        isPersonalized: true
      })
    }

    // Check if questions are currently being generated
    if (safetyData.questionGenerationTimestamp) {
      const generationTime = new Date(safetyData.questionGenerationTimestamp)
      const now = new Date()
      const timeDiff = now.getTime() - generationTime.getTime()
      
      // If questions were generated in the last 5 minutes, return existing questions
      if (timeDiff < 300000) {
        console.log('Questions were recently generated, returning existing questions...')
        if (personalizedQuestions && personalizedQuestions.length > 0) {
          return NextResponse.json({
            questions: personalizedQuestions,
            userPreferences: {
              tone: user.tone || 'gentle',
              voice: user.voice || 'friend',
              rawness: user.rawness || 'moderate',
              depth: user.depth || 'moderate',
              learning: user.learning || 'text',
              engagement: user.engagement || 'passive',
              goals: safetyData.goals || [],
              experience: safetyData.experience || 'beginner'
            },
            analysis: diagnosticAnalysis,
            isPersonalized: true
          })
        }
      }
    }

    // If we have existing questions, return them instead of regenerating
    if (personalizedQuestions && personalizedQuestions.length > 0) {
      console.log('Using existing personalized questions:', personalizedQuestions.length)
      return NextResponse.json({
        questions: personalizedQuestions,
        userPreferences: {
          tone: user.tone || 'gentle',
          voice: user.voice || 'friend',
          rawness: user.rawness || 'moderate',
          depth: user.depth || 'moderate',
          learning: user.learning || 'text',
          engagement: user.engagement || 'passive',
          goals: safetyData.goals || [],
          experience: safetyData.experience || 'beginner'
        },
        analysis: diagnosticAnalysis,
        isPersonalized: true
      })
    }

    // Check if questions are currently being generated globally
    if (isGeneratingQuestions) {
      console.log('Questions are currently being generated by another request, returning existing questions...')
      if (personalizedQuestions && personalizedQuestions.length > 0) {
        return NextResponse.json({
          questions: personalizedQuestions,
          userPreferences: {
            tone: user.tone || 'gentle',
            voice: user.voice || 'friend',
            rawness: user.rawness || 'moderate',
            depth: user.depth || 'moderate',
            learning: user.learning || 'text',
            engagement: user.engagement || 'passive',
            goals: safetyData.goals || [],
            experience: safetyData.experience || 'beginner'
          },
          analysis: diagnosticAnalysis,
          isPersonalized: true
        })
      }
    }

    console.log('No personalized questions found, generating them now...')
    isGeneratingQuestions = true
    
    // Generate personalized questions directly here
    try {
      const { AIOnboardingAnalyzer } = await import('../../../../lib/ai-onboarding-analyzer')
      
      // Extract onboarding data from user preferences
      const onboardingData = {
        tone: user.tone || 'gentle',
        voice: user.voice || 'friend',
        rawness: user.rawness || 'moderate',
        depth: user.depth || 'moderate',
        learning: user.learning || 'text',
        engagement: user.engagement || 'passive',
        goals: safetyData.goals || [],
        experience: safetyData.experience || 'beginner',
        timeCommitment: safetyData.timeCommitment || '30min',
        safety: {
          crisisSupport: safetyData.crisisSupport || false,
          contentWarnings: safetyData.contentWarnings || false,
          skipTriggers: safetyData.skipTriggers || false
        }
      }

      console.log('Generating personalized questions with data:', onboardingData)
      
      const analyzer = new AIOnboardingAnalyzer()
      const { analysis, questions } = await analyzer.analyzeOnboardingAndGenerateQuestions(onboardingData)

      console.log('Successfully generated questions:', questions.length)

      // Save the analysis and questions to the database
      const updatedSafety = {
        ...safetyData,
        diagnosticAnalysis: analysis,
        personalizedQuestions: questions,
        questionGenerationTimestamp: new Date().toISOString()
      }

      await db.update(users)
        .set({ safety: updatedSafety })
        .where(eq(users.id, userId))

                    console.log('Successfully saved personalized questions to database')
              isGeneratingQuestions = false

              return NextResponse.json({
                questions,
                userPreferences: {
                  tone: user.tone || 'gentle',
                  voice: user.voice || 'friend',
                  rawness: user.rawness || 'moderate',
                  depth: user.depth || 'moderate',
                  learning: user.learning || 'text',
                  engagement: user.engagement || 'passive',
                  goals: safetyData.goals || [],
                  experience: safetyData.experience || 'beginner'
                },
                analysis,
                isPersonalized: true
              })
          } catch (generateError) {
        console.error('Failed to generate personalized questions:', generateError)
        isGeneratingQuestions = false
        return NextResponse.json(
          { 
            error: 'Failed to generate personalized questions. Please try again.',
            details: generateError instanceof Error ? generateError.message : 'Unknown error'
          },
          { status: 500 }
        )
      }

  } catch (error) {
    console.error('Error getting diagnostic questions:', error)
    return NextResponse.json(
      { error: 'Failed to get diagnostic questions' },
      { status: 500 }
    )
  }
}
